checks:
    php:
        code_rating: true
        duplication: true
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/coverage/log/coverage.xml'
                coverage:
                    file: 'build/coverage/log/coverage.xml'
                    format: 'clover'
            - phpcs-run --ignore=*/tests/*,*/vendor/*
filter:
    paths: ['src/']